config/routes.rb
Depot::Application.routes.draw do
  get "admin" => "admin#index"

  controller :sessions do
    get 'login' => :new

    post 'login' => :create

    delete 'logout' => :destroy
end

  get "store/index"

scope '(:locale)' do
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :products do
    collection { post :import }
    get :who_bought, on: :member
  end
  root :to => "store#index", as: 'store'
end

  
   root :to => "store#index", as: 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
	<div class="navbar navbar-fixed-top">
		<%= form_tag store_path, class: 'locale' do %>
			<%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
			<%= submit_tag 'submit' %>
			<%= javascript_tag "$(.locale input).hide()" %>
		<% end %>
		<%= @page_title || t('.title') %>
	</div>

	<div id="columns">
		<div id="side">
			
			<div id="cart">
				<ul>
					<h4>Today is <%= Date.today %></h4>
				</ul>
				<% if @cart %>
					<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
					<%= render @cart %>
				<% end %>
			<% end %>
						
			<ul>
				<li><a href="#"><%= t('.home') %></a></li>
				<li><a href="#"><%= t('.question') %></a></li>
				<li><a href="#"><%= t('.news') %></a></li>
				<li><a href="#0"><%= t('.contact') %></a></li>
			</ul>

			<% if session[:user_id] %>
				<ul>
					<li><%= link_to "Orders", orders_path %></li>
					<li><%= link_to "Products", products_url %></li>
					<li><%= link_to "Users", users_path %></li>
				</ul>
				<%= button_to "Logout", logout_path, method: :delete %>
			<% end %>

			</div>
		</div>

		<div id="main">
			<%= yield %>
		</div>
	</div>

</body>
</html>